### ISSUE TITLE
I18n translations ?

### ISSUE THREAD

**Issue by anthony-robin** [thebestday/delayed-web#17]
That could be a good idea to add an I18n support in order to translate table columns, actions or messages !
Is there a way to add it easily ?

Thanks for this gem !

**Comment by coop** [comment]
Hi @anthony-robin, I'd probably recommend the [`i18n`](https://github.com/svenfuchs/i18n).

**Comment by anthony-robin** [comment]
Thanks for your reply, I already use i18n project but I was meaning in your gem.
Instead of setting titles and sentences directly in your code you could use:

``` html
<th>ID</th> <!-- I18n.t('delayed_web.id') -->
<th>Status</th> <!-- I18n.t('delayed_web.status') -->
<th>Created At</th> <!-- I18n.t('delayed_web.created_at') -->
<th>Run At</th> <!-- I18n.t('delayed_web.run_at') -->
<th>Attempts</th> <!-- I18n.t('delayed_web.attempts') -->
```

```yml
fr:
  delayed_web:
    id: Id
    status: Statut
    created_at: Ajouté le
    run_at: Démarré le
    attempts: Essais
...
```

Thanks !
